// Full Honor of Kings (Global server) hero roster, used to drive the Hero/Ban dropdown in
// DraftBoard.tsx so picks/bans always match one canonical spelling instead of being free-typed
// (a name typed slightly differently used to silently break the fearless-draft "already used"
// check and any hero-based stat grouping). Sourced from HoKStats.gg's Season 15.a tier list
// (2026-07-30), deduplicated and cross-checked against a manually compiled list - 115 heroes as
// of that date.
//
// TO ADD A NEW HERO: just add their name as a new string to this array (anywhere - it's
// alphabetized below only for readability, not required) and rebuild. Nothing else in the
// codebase needs to change - DraftBoard's dropdown reads straight from this array. The dropdown
// is backed by a <datalist>, not a locked <select>, so entering a hero not yet in this list still
// works (free-typed) in the meantime - it just won't autocomplete until added here.
export const HOK_HEROES: string[] = [
  "Agudo",
  "Alessio",
  "Allain",
  "Angela",
  "Annette",
  "Ao'yin",
  "Arke",
  "Arli",
  "Arthur",
  "Ata",
  "Athena",
  "Augran",
  "Bai Qi",
  "Biron",
  "Butterfly",
  "Cai Yan",
  "Chano",
  "Charlotte",
  "Chicha",
  "Cirrus",
  "Consort Yu",
  "Da Qiao",
  "Daji",
  "Devara",
  "Dharma",
  "Di Renjie",
  "Dian Wei",
  "Diaochan",
  "Dolia",
  "Donghuang",
  "Dr Bian",
  "Dun",
  "Dyadia",
  "Erin",
  "Fang",
  "Fatih",
  "Feyd",
  "Florentino",
  "Flowborn (Mage)",
  "Flowborn (Marksman)",
  "Flowborn (Tank)",
  "Fuzi",
  "Gan & Mo",
  "Garo",
  "Garuda",
  "Guan Yu",
  "Guiguzi",
  "Han Xin",
  "Haya",
  "Heino",
  "Hou Yi",
  "Huang Zhong",
  "Jing",
  "Kaizer",
  "Kongming",
  "Kui",
  "Lady Sun",
  "Lady Zhen",
  "Lam",
  "Lanling",
  "Lapulapu",
  "Li Bai",
  "Li Xin",
  "Lian Po",
  "Liang",
  "Liu Bang",
  "Liu Bei",
  "Liu Shan",
  "Lorion",
  "Lu Bu",
  "Luara",
  "Luban No.7",
  "Luna",
  "Mai Shiranui",
  "Marco Polo",
  "Mayene",
  "Meng Ya",
  "Menki",
  "Mi Yue",
  "Milady",
  "Ming",
  "Mozi",
  "Mulan",
  "Musashi",
  "Nakoruru",
  "Nezha",
  "Nuwa",
  "Pei",
  "Sakeer",
  "Shangguan",
  "Shi",
  "Shouyue",
  "Sima Yi",
  "Sun Bin",
  "Sun Ce",
  "Ukyo Tachibana",
  "Umbrosa",
  "Wang Zhaojun",
  "Wukong",
  "Wuyan",
  "Xiang Yu",
  "Xiao Qiao",
  "Xuance",
  "Yang Jian",
  "Yango",
  "Yao",
  "Yaria",
  "Ying",
  "Yixing",
  "Yuhuan",
  "Zhang Fei",
  "Zhou Yu",
  "Zhuangzi",
  "Zilong",
  "Ziya"
];
